services:
  mongodb:
    image: wishydocker/mongo:latest 
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    image: wishydocker/backend:latest 
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    depends_on:
      - mongodb

  frontend:
    image: wishydocker/frontend:latest
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data:
  node_modules: {}
